export const productsData = [
    {
        id: 1,
        image: "/chairs/img1.png",
        alt: "product 1 image",
        title: "Library Stool Chair",
        titleStyle: "text-[#4DBCC6]",
        // price: 20,
        discountedPrice: 20,
        sale: false,
        isNew: true,
        cartIcon: "/cart.svg",
        cartStyle: "bg-[#029FAE] text-[#000]",
    },
    {
        id: 2,
        image: "/chairs/img2.png",
        alt: "product 2 image",
        title: "Library Stool Chair",
        // titleStyle: "text-[#029FAE]",
        price: "$30",
        discountedPrice: 20,
        sale: true,
        isNew: false,
        cartIcon: "/cart.svg",
        cartStyle: "bg-[#F0F2F3] text-[#fff]",
    },
    {
        id: 3,
        image: "/chairs/img3.png",
        alt: "product 3 image",
        title: "Library Stool Chair",
        // titleStyle: "text-[#029FAE]",
        // price: 20,
        discountedPrice: 20,
        // isNew: true,
        cartIcon: "/cart.svg",
        cartStyle: "bg-[#F0F2F3] text-[#000]",
    },
    {
        id: 4,
        image: "/chairs/img4.png",
        alt: "product 4 image",
        title: "Library Stool Chair",
        // titleStyle: "text-[#029FAE]",
        // price: 20,
        discountedPrice: 20,
        isNew: false,
        cartIcon: "/cart.svg",
        cartStyle: "bg-[#F0F2F3] text-[#000]",
    },

]

export const topCategoriesData = [
    {
        id: 1,
        image: "/chairs/categorie1.png",
        alt: "product 1 image",
        title: "Wing Chair",
        titleStyle: "text-[#4DBCC6]",
        price: 20,
        discountedPrice: 20,
        sale: "New",
        isNew: true,
        cartIcon: "/cart.svg",
        cartStyle: "bg-[#029FAE] text-[#000]",
        productCount: "3,584 Products"
    },
    {
        id: 2,
        image: "/chairs/categorie2.png",
        alt: "product 2 image",
        title: "Wooden Chair",
        // titleStyle: "text-[#029FAE]",
        price: 30,
        discountedPrice: 20,
        sale: "Sales",
        isNew: false,
        cartIcon: "/cart.svg",
        cartStyle: "bg-[#F0F2F3] text-[#fff]",
        productCount: "157 Products"
    },
    {
        id: 3,
        image: "/chairs/categorie3.png",
        alt: "product 3 image",
        title: "Desk Chair",
        // titleStyle: "text-[#029FAE]",
        price: 20,
        discountedPrice: 20,
        isNew: true,
        cartIcon: "/cart.svg",
        cartStyle: "bg-[#F0F2F3] text-[#000]",
        productCount: "154 Products"
    },

]

export const exploreNewProductsData = [
    {
        id: 1,
        image: "/chairs/img4.png",
        alt: "product 1 image",
        title: "Library Stool Chair",
        titleStyle: "text-[#4DBCC6]",
        price: 20,
        discountedPrice: 20,
        sale: "New",
        isNew: true,
        cartIcon: "/cart.svg",
        cartStyle: "bg-[#029FAE] text-[#000]",
    },
    {
        id: 2,
        image: "/chairs/categorie4.png",
        alt: "product 2 image",
        title: "Library Stool Chair",
        // titleStyle: "text-[#029FAE]",
        price: 30,
        discountedPrice: 20,
        sale: "Sales",
        isNew: false,
        cartIcon: "/cart.svg",
        cartStyle: "bg-[#F0F2F3] text-[#fff]",
    },
    {
        id: 3,
        image: "/chairs/img2.png",
        alt: "product 3 image",
        title: "Library Stool Chair",
        // titleStyle: "text-[#029FAE]",
        price: 20,
        discountedPrice: 79.99,
        isNew: true,
        cartIcon: "/cart.svg",
        cartStyle: "bg-[#F0F2F3] text-[#000]",
    },
    {
        id: 4,
        image: "/chairs/img2.png",
        alt: "product 4 image",
        title: "Library Stool Chair",
        // titleStyle: "text-[#029FAE]",
        price: 20,
        discountedPrice: 20,
        isNew: false,
        cartIcon: "/cart.svg",
        cartStyle: "bg-[#F0F2F3] text-[#000]",
    },

]


export const products = [
    {
        id: 1,
        alt: "product 4 image",
        name: 'Classic White Chair',
        titleStyle: "text-[#4DBCC6]",
        price: 20,
        imageUrl: '/chairs/img2.png',
        isNew: true,
        cartIcon: "/cart.svg",
        cartStyle: "bg-[#029FAE] text-[#000]",

    },
    {
        id: 2,
        alt: "product 4 image",
        name: 'Pink Accent Chair',
        price: 20,
        originalPrice: 30,
        imageUrl: '/chairs/img1.png',
        isSale: true,
        cartIcon: "/cart.svg",
        cartStyle: "bg-[#F0F2F3] text-[#000]",

    },
    {
        id: 3,
        alt: "product 4 image",
        name: 'Modern Orange Chair',
        price: 20,
        imageUrl: '/chairs/img3.png',
        cartIcon: "/cart.svg",
        cartStyle: "bg-[#F0F2F3] text-[#000]",

    },
    {
        id: 4,
        alt: "product 4 image",
        name: 'Tufted Ivory Chair',
        price: 20,
        imageUrl: '/chairs/img4.png',
        cartIcon: "/cart.svg",
        cartStyle: "bg-[#F0F2F3] text-[#000]",

    },
    {
        id: 5,
        alt: "product 4 image",
        name: 'Designer Swivel Chair',
        price: 20,
        imageUrl: '/chairs/categorie2.png',
        isNew: true,
        cartIcon: "/cart.svg",
        cartStyle: "bg-[#029FAE] text-[#000]"

    },
    {
        id: 6,
        alt: "product 4 image",
        name: 'Gray Dining Chair',
        price: 20,
        originalPrice: 25,
        imageUrl: '/chairs/categorie4.png',
        isSale: true,
        cartIcon: "/cart.svg",
        cartStyle: "bg-[#F0F2F3] text-[#000]",

    },
    {
        id: 7,
        alt: "product 4 image",
        name: 'Modern Black Chair',
        price: 20,
        imageUrl: '/chairs/categorie5.png',
        cartIcon: "/cart.svg",
        cartStyle: "bg-[#F0F2F3] text-[#000]",

    },
    {
        id: 8,
        alt: "product 4 image",
        name: 'Vintage White Chair',
        price: 20,
        imageUrl: '/chairs/img2.png',
        cartIcon: "/cart.svg",
        cartStyle: "bg-[#F0F2F3] text-[#000]",

    },
    {
        id: 9,
        alt: "product 4 image",
        name: 'Vintage White Chair',
        price: 20,
        isNew:true,
        imageUrl: '/chairs/categorie1.png',
        cartIcon: "/cart.svg",
        cartStyle: "bg-[#029FAE] text-[#000]",

    },
    {
        id: 10,
        alt: "product 4 image",
        name: 'Pink Accent Chair',
        price: 20,
        originalPrice: 30,
        imageUrl: '/chairs/img1.png',
        isSale: true,
        cartIcon: "/cart.svg",
        cartStyle: "bg-[#F0F2F3] text-[#000]",

    },
    {
        id: 11,
        alt: "product 4 image",
        name: 'Modern Orange Chair',
        price: 20,
        imageUrl: '/chairs/img3.png',
        cartIcon: "/cart.svg",
        cartStyle: "bg-[#F0F2F3] text-[#000]",

    },
    {
        id: 12,
        alt: "product 4 image",
        name: 'Library Stool Chair',
        price: 20,
        imageUrl: '/chairs/categorie3.png',
        cartIcon: "/cart.svg",
        cartStyle: "bg-[#F0F2F3] text-[#000]",

    }
];